plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

# Layout
Layout/LineContinuationLeadingSpace:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**'

# Style
Style/Documentation:
  Enabled: false

# RSpec
RSpec/DescribeClass:
  Exclude:
    - 'spec/bin/**'

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4
